# Generated by Django 4.2.6 on 2024-02-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='auction_start',
            field=models.DateTimeField(null=True),
        ),
    ]
