# Generated by Django 4.2.6 on 2024-02-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_bid_bidder_delete_upcomingauctions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avail_bal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
