# Generated by Django 4.2.6 on 2024-02-19 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_bid_auction_listing_bid_current_bid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='auction',
            new_name='auction_name',
        ),
    ]
