# Generated by Django 4.2.6 on 2024-02-19 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_auction_bid_auction_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='auction_name',
        ),
    ]
