# Generated by Django 4.2.6 on 2024-04-22 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_auctionlisting_auctionpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='highest_bid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='highest_bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highest_bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='auctionpicture',
            field=models.ImageField(blank=True, default='goldpig.jpg', null=True, upload_to=''),
        ),
    ]
